language: elixir
elixir:
- 1.3.4
otp_release:
- 18.2.1
env:
- MIX_ENV=travis
services:
- postgresql
before_script:
- psql -c 'create database callforpapers_test;' -U postgres
notifications:
  slack:
    secure: nbLKxXoSLA86prCxRbXiLK8ArHKRmhArKAoyP5qsXcRW6mxMQVuaeY5UIusM7dYC1//ba/iQJ05FhNhqsr+cV4AP9WdnUkklHcmd3TuTGVEE5CMUJvBsKpMZZse3nHnVAdWkUQQY0cokrbpyEeysqjOgHNPsqyp2Y7mYLW6Ugtf0EEBgJYal6UBDQUn48hB3FLiF3IMiuQ0nlAse/rPh2m8pzb29nVGsj/UVOZ++iscV4qNyPPJRp7RnSiFg/87BQB3TSBWY+BzVXh0FbXpc5C95klcGQyTE+6YY0VPnvq/6mysPdzt/oPaTF53aN2cC7Fcx1rhXaz2IKbhg9W0vZVPYbVBtY1LECZxEBakmPqjvU83BeXFF+ykQLFkD/9gSAOp/cYNiHQgEr5vKyL3S9BuOfSyUIPcjEhW7qCafIlokzJxYTpr3LyAsuJVTDyg/bChJDfNbMyF6aYrHaJEQP4ooURxKlI5N5vGuoW3rPYkklyONYvG7UGlOF+Y3+9qt5x5MFq/qhRFETLZCgeRLjLAbdywMfYr0FyG+CxRh/s/jeGCmSq8Lv+cvmQoxFXe4rXAXa/T0vSQo6A8O/CDhQnU9UbM/R4y3x+gAdzExWqJq0jh0nCAdM7oceqS65OFET5Ra5z3pscOtajm8uKfAfwKOomTjjSDhRypW7lCaJMY=
deploy:
  provider: heroku
  api_key:
    secure: CEGULEYMmELNcc5Yrgetpy3HOiSoXXBTu3XQGEdBMMGqf5yLTug/Au8dqWfoRcaedv65qETn7bIc9YebbdHcwr1LJj4UFYHjrg+bWtzDUamzT39TFvx0eaZGA88uhZYx33ggkj1604zEc5AXPvyNinV4ixlQb14JWJfKP8uI4B1qAUbU2T/FgQz5uMzeZMNnx9AciUc21c0+l9cWiyg9n2u8YK6pXdey6Yi+c4rjI3ffNKpat+2BZ7p80805mxUNTPTW5N6DbrgxbrN2vl5dbP+iBqJNTlzEVQn+NidoX3/oeyRX9dgMd/p2CdEUpPsrG44ebl+GmoGg+afGM7EIl3KLSpzOK3m3iBn1V4gi2bqgQd/MJIh42LZbFtYb9co0qc2v9svmkp7lfEhbGVTwvjqdaGZbMhjARdq5RuRDBxkuvwn+fE5a4ZPlmDEyF/MLpg3n8wbemdNrdM14uMj5ZsRY1OLrsjf0CyNIdYcaDfeB13SCEZWg/tQ0P+2D2AQVm6ln0b5Z9TemhHPyRUv9ofMa5fOWJna+6pVVD6etYtayaodv252RAQBqeoKZBx44eekTlb8XQpur7bKClihvpYWma2INBoFEVNSyNbBVYT+xLQ2mQ1mh2rkSmPyjegqcUD1206ex1z55lrE97X7K7h3dh6xLY3WeJjQqYgqjBvU=
  app: callforpapers
  on:
    repo: koenighotze/callforpaper
