language: elixir
elixir:
- 1.3.4
otp_release:
- 18.2.1
env:
- MIX_ENV=travis
services:
- postgresql
before_script:
- psql -c 'create database callforpapers_test;' -U postgres
deploy:
  app: callforpapers
  api_key:
    secure: ueff2+OiPT6koARIN8iZCw/ej2uYxW2amygeddj+Npcv/CuDoWnZqyLAPKFfOMUJu0N7b6rWrQIsUj0/sMb26Bz2mQCqIUZv3B+ToGKGK7vHLCdW3DsnXRw9Yj1xUUdyueNVZPGCOcrZq8UD8io40j8noaz6SlfmJ85mNJ6Fk/tKXw73JzLuQJw8lbA72BiJDMyVov4uLHh/d50VLduja1iMvt5P673ZcYsTgQ2aeB53FAMc16UM4GZCSEJe25eC1GKff5i+XYxs7+KiIYEe9+TGnCNcR63+LX6p+jR/kGGbeWqbjyoo/y6CtUUXQWefIsQXyPZW4BATK8tzjo/JpyYFlMGD+s5sSgf5MjCri+aEvUftCwYZQo2yeBBQtx50R+YPbtJEmiJx8r6cO97lkMPE4JWxZqcf+aAvA10y/eY2QVD0IOA1jlysEZiNNssA8Aa/JC64m579Xc6RJctNb4lSpptmaILOCv1DNIg0IrAJjYZYYbiYapjfmb5e0Z+KdeeA3uSyuExCMhE2b0iHTKL+4thJp8wW6vvgGhrdfNiCJq5wXKjfNE4OYTWetc05EgM5UZ6C8KWDV+9L34zG1gEsR6Ixc5aR8KrR1UNVckdwJ5z2LYzyteDdIXZqpJyOJOET1FrxCmdEsJqQRlxaCKd9kN3T5R9UDi/6GxWobYU=
notifications:
  slack:
    secure: nbLKxXoSLA86prCxRbXiLK8ArHKRmhArKAoyP5qsXcRW6mxMQVuaeY5UIusM7dYC1//ba/iQJ05FhNhqsr+cV4AP9WdnUkklHcmd3TuTGVEE5CMUJvBsKpMZZse3nHnVAdWkUQQY0cokrbpyEeysqjOgHNPsqyp2Y7mYLW6Ugtf0EEBgJYal6UBDQUn48hB3FLiF3IMiuQ0nlAse/rPh2m8pzb29nVGsj/UVOZ++iscV4qNyPPJRp7RnSiFg/87BQB3TSBWY+BzVXh0FbXpc5C95klcGQyTE+6YY0VPnvq/6mysPdzt/oPaTF53aN2cC7Fcx1rhXaz2IKbhg9W0vZVPYbVBtY1LECZxEBakmPqjvU83BeXFF+ykQLFkD/9gSAOp/cYNiHQgEr5vKyL3S9BuOfSyUIPcjEhW7qCafIlokzJxYTpr3LyAsuJVTDyg/bChJDfNbMyF6aYrHaJEQP4ooURxKlI5N5vGuoW3rPYkklyONYvG7UGlOF+Y3+9qt5x5MFq/qhRFETLZCgeRLjLAbdywMfYr0FyG+CxRh/s/jeGCmSq8Lv+cvmQoxFXe4rXAXa/T0vSQo6A8O/CDhQnU9UbM/R4y3x+gAdzExWqJq0jh0nCAdM7oceqS65OFET5Ra5z3pscOtajm8uKfAfwKOomTjjSDhRypW7lCaJMY=
