language: elixir
elixir:
- 1.3.4
otp_release:
- 18.2.1
env:
- MIX_ENV=travis
services:
- postgresql
before_script:
- psql -c 'create database callforpapers_test;' -U postgres
- psql -c 'create database conference_test;' -U postgres
- psql -c 'create database ratings_test;' -U postgres
